"""empty message

Revision ID: 47b3cc08a0e3
Revises: 
Create Date: 2022-01-29 22:47:41.230502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b3cc08a0e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('current', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('is_input', sa.Boolean(), nullable=True),
    sa.Column('is_select', sa.Boolean(), nullable=True),
    sa.Column('is_check', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wax_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('private_token', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('private_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wax_account')
    op.drop_table('user')
    op.drop_table('settings')
    # ### end Alembic commands ###
