"""empty message

Revision ID: 4f4b525a6a1f
Revises: e1bbaf206d77
Create Date: 2022-01-30 20:14:30.013686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4b525a6a1f'
down_revision = 'e1bbaf206d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wax_account', sa.Column('drop_balance', sa.Float(), nullable=True))
    op.add_column('wax_account', sa.Column('balance', sa.Float(), nullable=True))
    op.add_column('wax_account', sa.Column('cpu', sa.Float(), nullable=True))
    op.add_column('wax_account', sa.Column('ram', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wax_account', 'ram')
    op.drop_column('wax_account', 'cpu')
    op.drop_column('wax_account', 'balance')
    op.drop_column('wax_account', 'drop_balance')
    # ### end Alembic commands ###
