"""empty message

Revision ID: 98ace5e72c35
Revises: b0df6cd8e413
Create Date: 2022-02-07 04:51:31.127312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ace5e72c35'
down_revision = 'b0df6cd8e413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wax_account', sa.Column('rpc', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wax_account', 'rpc')
    # ### end Alembic commands ###
