"""empty message

Revision ID: e1bbaf206d77
Revises: 47b3cc08a0e3
Create Date: 2022-01-30 01:51:00.916015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1bbaf206d77'
down_revision = '47b3cc08a0e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wax_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('private_token', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('private_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wax_account')
    # ### end Alembic commands ###
