"""empty message

Revision ID: e1faef576bda
Revises: 4f4b525a6a1f
Create Date: 2022-01-30 22:04:45.337406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1faef576bda'
down_revision = '4f4b525a6a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wax_account', sa.Column('update_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wax_account', 'update_time')
    # ### end Alembic commands ###
